apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internal-api-portal-data
  namespace: internal-api-portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
